# Generated by Django 3.1.7 on 2021-05-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_auto_20210501_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='artist_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapi.artists'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracks',
            name='album_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='webapi.albums'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albums',
            name='artist_id',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='album_id',
            field=models.CharField(max_length=22),
        ),
    ]
